name: Backend (API) tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test-backend-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Create test private key for signing alerts
        run: ssh-keygen -m PKCS8 -t ecdsa -f $(pwd)/test-key

      - name: Start PostgreSQL Docker container for testing
        run: docker-compose -f docker-compose-test-api.yml up -d

      - name: Run backend API tests
        run: npm run test:api
        env:
          BASE_URL: http://example.com
          VERIFIER_EMAIL: ifrc@example.com
          PRIVATE_KEY_FILENAME: test-key
          TLS_DIRECTORY: ./
